-- STEG 1: Arkiver alle eksisterende stillinger
UPDATE job_postings SET status = 'archived', published_at = NULL WHERE status = 'active';

-- STEG 2: Legg inn 13 nye stillinger (enkle beskrivelser)

INSERT INTO public.job_postings (title, slug, description, short_description, job_type, category, status, location, fylke, kommune, region, company_name, vessel_name, salary_min, salary_max, salary_text, start_date, application_deadline, published_at, contact_email, contact_phone, meta_title, meta_description) VALUES
('Matros - Servicefartøy', 'matros-servicefartoy', 'Bluecrew rekrutterer løpende matroser til servicefartøy for våre kunder innen havbruk og maritim sektor. Krav: Gyldig STCW-sertifikater, D5/D6 sertifikat ønskelig, erfaring fra servicefartøy eller havbruk. Vi tilbyr konkurransedyktig lønn, varierte oppdrag langs kysten og fleksible rotasjonsordninger. Dette er løpende rekruttering - vi kontakter deg når relevante oppdrag dukker opp.', 'Løpende rekruttering av matroser til servicefartøy.', 'Fast', 'Dekk', 'active', 'Vestland / Trøndelag', 'Vestland', 'Bergen', 'Vestlandet', NULL, NULL, 620000, 750000, 'Konkurransedyktig lønn', NULL, '2026-12-31', NOW(), 'post@bluecrew.no', '+47 77 02 90 00', 'Matros Servicefartøy | Bluecrew', 'Søk stilling som matros på servicefartøy.');

INSERT INTO public.job_postings (title, slug, description, short_description, job_type, category, status, location, fylke, kommune, region, company_name, vessel_name, salary_min, salary_max, salary_text, start_date, application_deadline, published_at, contact_email, contact_phone, meta_title, meta_description) VALUES
('Matros - Subsea/Offshore', 'matros-subsea-offshore', 'Bluecrew søker kontinuerlig etter matroser til subsea- og offshore-operasjoner. Krav: Gyldig STCW-sertifikater, offshore sikkerhetskurs (BOSIET/HUET), minimum 1 års erfaring fra offshore og god fysikk. Vi tilbyr konkurransedyktig lønn og 2-2-2-4 eller lignende turnus. Løpende rekruttering.', 'Løpende rekruttering av matroser til subsea og offshore.', 'Fast', 'Dekk', 'active', 'Stavanger / Bergen', 'Rogaland', 'Stavanger', 'Sørlandet', NULL, NULL, 700000, 850000, 'Konkurransedyktig lønn', NULL, '2026-12-31', NOW(), 'post@bluecrew.no', '+47 77 02 90 00', 'Matros Subsea Offshore | Bluecrew', 'Søk stilling som matros innen subsea og offshore.');

INSERT INTO public.job_postings (title, slug, description, short_description, job_type, category, status, location, fylke, kommune, region, company_name, vessel_name, salary_min, salary_max, salary_text, start_date, application_deadline, published_at, contact_email, contact_phone, meta_title, meta_description) VALUES
('Styrmann - Kystfart', 'styrmann-kystfart', 'Vi rekrutterer løpende styrmann til kystfart og servicefartøy. Kvalifikasjoner: D4 eller D5 sertifikat, GOC, erfaring fra servicefartøy eller kystfart. Vi tilbyr attraktiv lønn og varierte oppdrag langs norskekysten. Registrer deg for løpende vurdering.', 'Løpende rekruttering av styrmann til kystfart.', 'Fast', 'Dekk', 'active', 'Hele kysten', 'Vestland', 'Bergen', 'Vestlandet', NULL, NULL, 750000, 900000, 'Konkurransedyktig lønn', NULL, '2026-12-31', NOW(), 'post@bluecrew.no', '+47 77 02 90 00', 'Styrmann Kystfart | Bluecrew', 'Søk stilling som styrmann i kystfart.');

INSERT INTO public.job_postings (title, slug, description, short_description, job_type, category, status, location, fylke, kommune, region, company_name, vessel_name, salary_min, salary_max, salary_text, start_date, application_deadline, published_at, contact_email, contact_phone, meta_title, meta_description) VALUES
('Overstyrmann - Offshore', 'overstyrmann-offshore', 'Bluecrew søker erfarne overstyrmenn til offshore-operasjoner. Krav: D3 sertifikat eller høyere, DP sertifikat (Unlimited foretrukket), offshore sikkerhetssertifikater, erfaring fra PSV, AHTS eller CSV. Vi tilbyr høy lønn og attraktive rotasjonsordninger.', 'Overstyrmann søkes til offshore. DP-erfaring.', 'Fast', 'Dekk', 'active', 'Stavanger / Bergen', 'Rogaland', 'Stavanger', 'Sørlandet', NULL, NULL, 850000, 1050000, 'Konkurransedyktig lønn', NULL, '2026-12-31', NOW(), 'post@bluecrew.no', '+47 77 02 90 00', 'Overstyrmann Offshore | Bluecrew', 'Søk stilling som overstyrmann offshore.');

INSERT INTO public.job_postings (title, slug, description, short_description, job_type, category, status, location, fylke, kommune, region, company_name, vessel_name, salary_min, salary_max, salary_text, start_date, application_deadline, published_at, contact_email, contact_phone, meta_title, meta_description) VALUES
('Skipsfører D6 - Havbruk', 'skipsforer-d6-havbruk', 'Vi søker kontinuerlig etter skipsførere med D6 til oppdrag innen havbruksnæringen. Kvalifikasjoner: D6 sertifikat, lokalkjennskap til kystfarvann, erfaring fra havbruk/servicefartøy og lederegenskaper. Vi tilbyr svært konkurransedyktig lønn og fleksible turnusordninger.', 'Skipsfører D6 søkes til havbruk.', 'Fast', 'Dekk', 'active', 'Nord-Norge / Trøndelag', 'Troms og Finnmark', 'Tromsø', 'Nord-Norge', NULL, NULL, 900000, 1150000, 'Konkurransedyktig lønn', NULL, '2026-12-31', NOW(), 'post@bluecrew.no', '+47 77 02 90 00', 'Skipsfører D6 Havbruk | Bluecrew', 'Søk stilling som skipsfører D6 i havbruk.');

INSERT INTO public.job_postings (title, slug, description, short_description, job_type, category, status, location, fylke, kommune, region, company_name, vessel_name, salary_min, salary_max, salary_text, start_date, application_deadline, published_at, contact_email, contact_phone, meta_title, meta_description) VALUES
('Maskinist M3/M4', 'maskinist-m3-m4', 'Bluecrew rekrutterer løpende maskinister med M3 eller M4 sertifikat. Krav: M3 eller M4 maskinistbevis, erfaring fra mindre/mellomstore fartøy, teknisk forståelse og vedlikeholdserfaring. Vi tilbyr god lønn og varierte oppdrag innen kystfart og havbruk.', 'Maskinist M3/M4 søkes. Løpende rekruttering.', 'Fast', 'Maskin', 'active', 'Hele kysten', 'Vestland', 'Bergen', 'Vestlandet', NULL, NULL, 750000, 900000, 'Konkurransedyktig lønn', NULL, '2026-12-31', NOW(), 'post@bluecrew.no', '+47 77 02 90 00', 'Maskinist M3 M4 | Bluecrew', 'Søk stilling som maskinist M3/M4.');

INSERT INTO public.job_postings (title, slug, description, short_description, job_type, category, status, location, fylke, kommune, region, company_name, vessel_name, salary_min, salary_max, salary_text, start_date, application_deadline, published_at, contact_email, contact_phone, meta_title, meta_description) VALUES
('Maskinsjef - Offshore', 'maskinsjef-offshore', 'Vi søker erfarne maskinsjefer til offshore-operasjoner. Kvalifikasjoner: M1 eller M2 maskinsjefbevis, DP-erfaring, offshore sikkerhetssertifikater og ledererfaring. Vi tilbyr svært høy lønn og attraktiv turnus (2-2-2-4 eller lignende).', 'Maskinsjef søkes til offshore.', 'Fast', 'Maskin', 'active', 'Stavanger / Bergen', 'Rogaland', 'Stavanger', 'Sørlandet', NULL, NULL, 1000000, 1350000, 'Konkurransedyktig lønn', NULL, '2026-12-31', NOW(), 'post@bluecrew.no', '+47 77 02 90 00', 'Maskinsjef Offshore | Bluecrew', 'Søk stilling som maskinsjef offshore.');

INSERT INTO public.job_postings (title, slug, description, short_description, job_type, category, status, location, fylke, kommune, region, company_name, vessel_name, salary_min, salary_max, salary_text, start_date, application_deadline, published_at, contact_email, contact_phone, meta_title, meta_description) VALUES
('ETO - Fremtidige oppdrag', 'eto-fremtidige-oppdrag', 'Bluecrew bygger database over kvalifiserte ETOer for kommende oppdrag innen offshore og cruise. Krav: ETO-sertifikat, DP-erfaring ønskelig, erfaring med automasjon og elektronikk. Registrer deg nå for å bli vurdert til fremtidige oppdrag.', 'ETO søkes til fremtidige oppdrag.', 'Fast', 'Teknisk', 'active', 'Hele Norge', 'Rogaland', 'Stavanger', 'Sørlandet', NULL, NULL, 800000, 1000000, 'Konkurransedyktig lønn', NULL, '2026-12-31', NOW(), 'post@bluecrew.no', '+47 77 02 90 00', 'ETO Stilling | Bluecrew', 'Registrer deg som ETO hos Bluecrew.');

INSERT INTO public.job_postings (title, slug, description, short_description, job_type, category, status, location, fylke, kommune, region, company_name, vessel_name, salary_min, salary_max, salary_text, start_date, application_deadline, published_at, contact_email, contact_phone, meta_title, meta_description) VALUES
('ROV-Pilot - Fremtidige oppdrag', 'rov-pilot-fremtidige-oppdrag', 'Vi bygger nettverk av kvalifiserte ROV-piloter for kommende subsea-oppdrag. Krav: ROV Pilot sertifikat, erfaring fra offshore/subsea operasjoner, offshore sikkerhetssertifikater. Meld din interesse for fremtidige oppdrag med høy lønn.', 'ROV-Pilot søkes til fremtidige subsea-oppdrag.', 'Fast', 'Teknisk', 'active', 'Stavanger / Bergen', 'Rogaland', 'Stavanger', 'Sørlandet', NULL, NULL, 950000, 1250000, 'Konkurransedyktig lønn', NULL, '2026-12-31', NOW(), 'post@bluecrew.no', '+47 77 02 90 00', 'ROV Pilot | Bluecrew', 'Registrer deg som ROV-pilot hos Bluecrew.');

INSERT INTO public.job_postings (title, slug, description, short_description, job_type, category, status, location, fylke, kommune, region, company_name, vessel_name, salary_min, salary_max, salary_text, start_date, application_deadline, published_at, contact_email, contact_phone, meta_title, meta_description) VALUES
('Driftsoperatør - Oppdrett', 'driftsoperator-oppdrett', 'Bluecrew søker kontinuerlig etter driftsoperatører til oppdrettsnæringen. Krav: Båtførerbevis, erfaring fra oppdrett ønskelig, praktisk anlagt. Vi tilbyr god lønn og oppdrag i Nord-Norge og Trøndelag med gode turnusordninger.', 'Driftsoperatør søkes til oppdrett.', 'Fast', 'Dekk', 'active', 'Nord-Norge / Trøndelag', 'Troms og Finnmark', 'Tromsø', 'Nord-Norge', NULL, NULL, 700000, 850000, 'Konkurransedyktig lønn', NULL, '2026-12-31', NOW(), 'post@bluecrew.no', '+47 77 02 90 00', 'Driftsoperatør Oppdrett | Bluecrew', 'Søk stilling som driftsoperatør i oppdrett.');

INSERT INTO public.job_postings (title, slug, description, short_description, job_type, category, status, location, fylke, kommune, region, company_name, vessel_name, salary_min, salary_max, salary_text, start_date, application_deadline, published_at, contact_email, contact_phone, meta_title, meta_description) VALUES
('Driftsoperatør m/D6 - Havbruk', 'driftsoperator-d6-havbruk', 'Vi søker driftsoperatører med D6 sertifikat til havbruksnæringen. Krav: D6 sertifikat, kranførerbevis ønskelig, erfaring fra oppdrett/havbruk. Vi tilbyr svært god lønn og varierte arbeidsoppgaver langs hele kysten.', 'Driftsoperatør med D6 søkes til havbruk.', 'Fast', 'Dekk', 'active', 'Vestland / Trøndelag', 'Vestland', 'Bergen', 'Vestlandet', NULL, NULL, 800000, 950000, 'Konkurransedyktig lønn', NULL, '2026-12-31', NOW(), 'post@bluecrew.no', '+47 77 02 90 00', 'Driftsoperatør D6 Havbruk | Bluecrew', 'Søk stilling som driftsoperatør med D6 i havbruk.');

INSERT INTO public.job_postings (title, slug, description, short_description, job_type, category, status, location, fylke, kommune, region, company_name, vessel_name, salary_min, salary_max, salary_text, start_date, application_deadline, published_at, contact_email, contact_phone, meta_title, meta_description) VALUES
('Forpleiningsassistent - Offshore/Kyst', 'forpleiningsassistent-offshore', 'Bluecrew rekrutterer løpende forpleiningsassistenter til offshore og kystfart. Krav: Hygienesertifikat, STCW grunnkurs, serviceinnstilt. Vi tilbyr god lønn, kost og losji på oppdrag, og mulighet for karriereutvikling.', 'Forpleiningsassistent søkes til offshore og kyst.', 'Fast', 'Catering', 'active', 'Hele kysten', 'Rogaland', 'Stavanger', 'Sørlandet', NULL, NULL, 550000, 680000, 'Konkurransedyktig lønn', NULL, '2026-12-31', NOW(), 'post@bluecrew.no', '+47 77 02 90 00', 'Forpleiningsassistent | Bluecrew', 'Søk stilling som forpleiningsassistent.');

INSERT INTO public.job_postings (title, slug, description, short_description, job_type, category, status, location, fylke, kommune, region, company_name, vessel_name, salary_min, salary_max, salary_text, start_date, application_deadline, published_at, contact_email, contact_phone, meta_title, meta_description) VALUES
('Forpleiningssjef - Offshore', 'forpleiningssjef-offshore', 'Vi søker erfarne forpleiningssjefer til offshore-plattformer og fartøy. Kvalifikasjoner: Fagbrev kokk, ledererfaring fra storkjøkken, offshore sikkerhetskurs. Vi tilbyr høy lønn og attraktive rotasjonsordninger.', 'Forpleiningssjef søkes til offshore.', 'Fast', 'Catering', 'active', 'Stavanger / Bergen', 'Rogaland', 'Stavanger', 'Sørlandet', NULL, NULL, 750000, 920000, 'Konkurransedyktig lønn', NULL, '2026-12-31', NOW(), 'post@bluecrew.no', '+47 77 02 90 00', 'Forpleiningssjef Offshore | Bluecrew', 'Søk stilling som forpleiningssjef offshore.');
